# Params Configuration for the Alpha Theme
# This file defines custom parameters specific to the Alpha theme.
#
# Documentation: https://alpha.oxypteros.com/docs/config/params-toml/

# Site Appearance
# ---------------------
# Displays a text-based logo from the first letter of the site's title.
pseudologo_enabled = true
# The year your site was established, shown in the footer.
established_year = "2025"
# A motto or tagline displayed in the footer. Use a backslash (\) to escape
# quotes.
motto = "\"Unleash your words\""

# Privacy
# ---------------------
# Shows a settings modal for visitors to manage settings (tracking, prefetch).
visitor_settings = true
# Displays a banner about the site's privacy policy (cookies, etc.)
noCookies_snackbar = true

# Integrations
# ---------------------
# Enables Pagefind client-side search (requires installation).
pagefind_enabled   = false
# Enables GoatCounter analytics. Enter your site code here. (requires sign-up)
goatcounter_prefix = ""

# Performance
# ---------------------
# Preloads linked pages for faster navigation.
prefetch_enabled = true

# Global SEO 
# ---------------------
# Place the global image for sharing in `assets/img/`. Fill only the filename.
# Ex. "sharing-default.jpg"
seo_default_image = "" # Overridden by `seo_image` in page front matter.
# Place the logo image in `assets/img/`. Fill only the filename. 
# Ex: "logo.png"
seo_logo_path = "" 
# Fill with a license URL. 
# Ex. "https://creativecommons.org/licenses/by/4.0/"
seo_license = "" # Overridden by `license` in page front matter. 
# Fill your organization/company name.
seo_organization = "" # Defaults to site title.
# Fill with a name
seo_author = ""  # Overridden by `author` in page front matter.
# URL to your author profile for open-graph (FB, Linkedin)
seo_author_url = "" 
# Your site's @handle for the `twitter:site` tag in Twitter Cards
seo_twitter_username = "" # Fills `twitter:site` in twitter-cards

# PWA Manifest Settings
# ---------------------
seo_manifest_short_name  = "" # Short name for the PWA homescreen icon.
seo_manifest_theme_color = "" # UI color for PWA. Ex: "#ffffff"
seo_manifest_bg_color    = "" # Splash screen background color. Ex: "#000000"

# Development Settings
# ---------------------
# Run `npm install` from root to develop the theme
tailwind_enabled = false # Enables full Tailwind CSS for development.

# LiVa Settings (Linting Validator by Oxy)
# ---------------------
liva_enabled = true     # Enables on-page validation messages from LiVa.
livaWarn_enabled = true # Enables terminal warning messages from LiVa.
